### ISSUE TITLE
publishLocal.sh does not exist

### ISSUE THREAD

**Issue by m1cm1c** [ShiftLeftSecurity/codepropertygraph#1024]
The main readme of this repository says:

> Additional build-time dependencies are automatically downloaded as part of the build process. To build and install into your local Maven cache, issue the command `./publishLocal.sh`.

However, there is no file `./publishLocal.sh`.

**Comment by ursachec** [comment]
Thanks for the report @m1cm1c! Closing this as the README does not contain that broken reference any more
