### ISSUE TITLE
Duplicate REACHING_DEF edges

### ISSUE THREAD

**Issue by m1cm1c** [ShiftLeftSecurity/codepropertygraph#1084]
REACHING_DEF edges between RETURN nodes and their corresponding CALL nodes exist twice.

**Comment by fabsx00** [comment]
Can you provide a sample code snippet on which this happened? Not sure what you mean exactly.

**Comment by m1cm1c** [comment]
```
int foo() {
  return bar();
}
```

The CALL to `bar()` has ID `1000105L`:
```
  Call(
    id -> 1000105L,
    code -> "bar()",
    name -> "bar",
    order -> 1,
    methodInstFullName -> None,
    methodFullName -> "bar",
    argumentIndex -> 1,
    dispatchType -> "STATIC_DISPATCH",
    signature -> "TODO assignment signature",
    typeFullName -> "ANY",
    dynamicTypeHintFullName -> List(),
    lineNumber -> Some(2),
    columnNumber -> Some(9),
    resolved -> None,
    depthFirstOrder -> None,
    internalFlags -> None
  )
  ```
I'm using an ID to make sure that there is only a single node in the traversal.

Then run `run.ossdataflow` and:
```
joern> cpg.call.id(1000105L).outE(EdgeTypes.REACHING_DEF).inV.l 
res8: List[Node] = List(
  Return(
    id -> 1000104L,
    lineNumber -> Some(2),
    columnNumber -> Some(2),
    order -> 1,
    argumentIndex -> 1,
    code -> "return bar();",
    depthFirstOrder -> None,
    internalFlags -> None
  ),
  Return(
    id -> 1000104L,
    lineNumber -> Some(2),
    columnNumber -> Some(2),
    order -> 1,
    argumentIndex -> 1,
    code -> "return bar();",
    depthFirstOrder -> None,
    internalFlags -> None
  )
)
```

The edge is attached twice to the nodes involved:
```
joern> cpg.call.id(1000105L).outE(EdgeTypes.REACHING_DEF).l 
res9: List[Edge] = List(
  io.shiftleft.codepropertygraph.generated.edges.ReachingDef@7e66ecb3,
  io.shiftleft.codepropertygraph.generated.edges.ReachingDef@7e66ecb3
)

joern> cpg.all.id(1000104L).inE(EdgeTypes.REACHING_DEF).l 
res10: List[Edge] = List(
  io.shiftleft.codepropertygraph.generated.edges.ReachingDef@7e66ecb3,
  io.shiftleft.codepropertygraph.generated.edges.ReachingDef@7e66ecb3
)
```

**Comment by fabsx00** [comment]
Ok, thanks, looking...

**Comment by fabsx00** [comment]
Thanks! Got a fix ready. One thing I'd want to point out: if you're looking to walk along the DDG, you'll probably be happier using the `ddgIn` method that is defined on `TrackingPoints`. That method takes into account the semantics specified in `default.semantics`. Otherwise, you'll end up with quite a few REACHING_DEF edges that shouldn't be present.

https://github.com/ShiftLeftSecurity/codepropertygraph/blob/master/dataflowengineoss/src/main/scala/io/shiftleft/dataflowengineoss/language/nodemethods/TrackingPointMethods.scala#L35

Becomes available via `import io.shiftleft.dataflowengineoss.language._`.

**Comment by m1cm1c** [comment]
Thank you! What turned me away from using `ddgIn` is that there is no `ddgOut`. However, I think I just managed to write a `ddgOut` method. It's pretty hacky because I do not understand how `ddgIn` works (it's distributed over too many files and other functions that are called) but I think that it should work. If anyone else needs it:

```
implicit class MyTrackingPointTraversals(input: Traversal[nodes.TrackingPoint]) {
  def ddgOut = {
    var resultNodes = List[nodes.TrackingPoint]()
    val inputL = input.l
    for(inputNode <- inputL) {
      val candidates = Traversal(inputNode).outE(EdgeTypes.REACHING_DEF).inV.l
      val newResultNodes = candidates.filter(_.isInstanceOf[nodes.TrackingPoint]).cast[nodes.TrackingPoint].filter(candidate => Traversal(candidate).ddgIn.l.contains(inputNode)).l
      resultNodes = List.concat(resultNodes, newResultNodes)
    }
    Traversal(resultNodes)
  }
}
```
