### ISSUE TITLE
Extracting graphs from .cpp files

### ISSUE THREAD

**Issue by maximzubkov** [ShiftLeftSecurity/codepropertygraph#1163]
Hello! My name is Maksim Zubkov, I am a bachelor's student at MIPT, Russia, and an inter at JetBrains Research. 
Thank you for your work on `Joern` it is impressive!

Under the scope of my undergraduate thesis at JetBrains Research, I am working on a source code understanding problem using ML methods. I used `Joern` to extract the CPG  from code written in C++. Firstly I tried to extract CPG directly using `importCode` but came across the same issue as @muoitranduc ([Issue](https://github.com/ShiftLeftSecurity/joern/issues/487)). 
Then I tried the following commands:
```
$ joern-parse my_file.cpp
$ joern
     ██╗ ██████╗ ███████╗██████╗ ███╗   ██╗
     ██║██╔═══██╗██╔════╝██╔══██╗████╗  ██║
     ██║██║   ██║█████╗  ██████╔╝██╔██╗ ██║
██   ██║██║   ██║██╔══╝  ██╔══██╗██║╚██╗██║
╚█████╔╝╚██████╔╝███████╗██║  ██║██║ ╚████║
 ╚════╝  ╚═════╝ ╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝
$ joern> loadCpg(inputPath="cpg.bin") 
```
And everything seems to work correctly!

Due to this fact, I decided to check why `importCfg` and  `importCode` has different behavior. Here is what I have found:
1. According to the code ([link](https://github.com/ShiftLeftSecurity/joern/blob/75f4435c39bef9d17f8e3b1945536d7a05a258ce/joern-cli/src/main/scala/io/shiftleft/joern/JoernParse.scala#L67)) of `joern-parse` all the following extensions are supported: `[".c", ".cc", ".cpp", ".h", ".hpp"]`
2. On the other hand, the problem with `importCode` may occur because extensions argument in `runAndOutput` function ([link](https://github.com/ShiftLeftSecurity/codepropertygraph/blob/024f1cda27296638ec8d4fd47ecc60b9ae39c542/console/src/main/scala/io/shiftleft/console/cpgcreation/FuzzyCCpgGenerator.scala#L23)). As I understand if we simply change `Set(".c")` to `Set(".c", ".cc", ".cpp", ".h", ".hpp")` nothing will go wrong, am I right?

Best regards, Maksim

**Comment by muoitranduc** [comment]
Great! It works well on my machine now. 
Thanks so much for this!

**Comment by itsacoderepo** [comment]
Related PR: https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1165

We will merge it as soon as we fixed the GH actions ..

**Comment by maximzubkov** [comment]
I guess now we can close the issue
