### ISSUE TITLE
RFC: rename semanticcpg.language.types.expressions.Call -> CallExt etc. 

### ISSUE THREAD

**Issue by mpollmeier** [ShiftLeftSecurity/codepropertygraph#1233]
I'd like to rename all traversal extension classes like e.g.  `semanticcpg.language.types.expressions.Call` to `semanticcpg.language.types.expressions.CallTrav`. 

Motivation: that enables us to drop the `nodes.` prefix everywhere. It somehow became a norm in our codebase to refer to node types with the explict prefix, e.g. `nodes.Call`. The more I see that pattern the less I like it, and yes I started it, but I feel sorry about it. 

Before I go ahead and create a monster PR I thought I'd ask for feedback. 
Please select one of the following options: yes|no|dontcare

**Comment by ml86** [comment]
I am all for it.I already suggest it 1-2 years back but did not come through with it. So hoping for the best now.

**Comment by mpollmeier** [comment]
Just tried to do the same for the codescience repo, but unfortunately things are more complicated there...
Shadowing implicits in generated code and cpg repo, yet again a different naming convention make it quite complicated to clean up and standardise the codescience repo. 
I'll put this on hold until we've migrated to Scala3, where extension methods don't need to be in (named) classes any more.
