### ISSUE TITLE
namespace c++ keyword causes unhandled nodes

### ISSUE THREAD

**Issue by thapr0digy** [ShiftLeftSecurity/codepropertygraph#1320]
Just started testing the new c2cpg parser after looking at this Github issue from joern: https://github.com/joernio/joern/issues/533

**Problem**
Generating a cpg for a C program using the C++ keyword 'namespace' generates preprocessor errors and problems

**Expected behavior**
I expect for it to proceed with the parsing without any issues. 

**Actual behavior**
I noticed with this basic testcase, it fails to handle an integer with the variable name "namespace" and shows there to be a preprocessor error and 1 problem. 

Here is the output from the c2cpg script for my sample testcase:

```
$ ./c2cpg.sh /tmp/testcase
[INFO ] Output file exists, removing: cpg.bin
[INFO ] initializing 0 nodes from existing storage - this may take some time
[INFO ] installed GC monitors. will clear references if heap (after GC) is larger than 80%
[INFO ] Start of enhancement: io.shiftleft.semanticcpg.passes.metadata.MetaDataPass
[INFO ] Enhancement io.shiftleft.semanticcpg.passes.metadata.MetaDataPass completed in 55 milliseconds
[INFO ] Start of enhancement: io.shiftleft.c2cpg.passes.AstCreationPass
[INFO ] Parsed '/tmp/testcase/testcase.c' in 294.4 ms (1 preprocessor error(s), 1 problems)
[WARN ] Node 'CPPASTNamespaceAlias' not handled yet!
  Code: 'namespace = argc;'
  File: '/tmp/testcase/testcase.c'
  Line: 5

[INFO ] Enhancement io.shiftleft.c2cpg.passes.AstCreationPass completed in 408 milliseconds
[INFO ] Start of enhancement: io.shiftleft.semanticcpg.passes.CfgCreationPass
[INFO ] Enhancement io.shiftleft.semanticcpg.passes.CfgCreationPass completed in 31 milliseconds
[INFO ] Start of enhancement: io.shiftleft.c2cpg.passes.StubRemovalPass
[INFO ] Enhancement io.shiftleft.c2cpg.passes.StubRemovalPass completed in 2 milliseconds
[INFO ] Start of enhancement: io.shiftleft.semanticcpg.passes.typenodes.TypeNodePass
[INFO ] Enhancement io.shiftleft.semanticcpg.passes.typenodes.TypeNodePass completed in 3 milliseconds
[INFO ] progress of clearing references: 100.00%
[INFO ] cleared all clearable references
```

testcase.c

```
#include <stdio.h>

int main(int argc, char **argv) {
        int namespace;
        namespace = argc;
        return 0;
}
```

Please let me know if there's anything else needed here as I'm going to assume that this will likely have the same issue with other keywords.

**Comment by thapr0digy** [comment]
For reference, in this testcase it generates a CPPAstNamespaceAlias error, but in another codebase it generates the following:

```
[WARN ] Parse problem 'CPPASTProblem' occurred!
  Code: 'int namespace;'
  File: '/home/jgalindo/GitProjects/codebase.c'
  Line: 3511
```

I'm leaving out the codebase, but if it's necessary let me know.

**Comment by max-leuthaeuser** [comment]
I can confirm this issue. Thanks for the report. 
It will be fixed soon (tm) whenever I got time for it.

Background: we internally use the Eclipse CDT preprocessor and parser but currently in CPP mode only.
As your code is valid C but not C++ (try it with https://www.onlinegdb.com/online_c++_compiler for example) where namespace is a reserved keyword this simple approach will fail. In the future I will run the appropriate parser of course.
