### ISSUE TITLE
columnNumber seems to be messed up when using the new cpg parser 

### ISSUE THREAD

**Issue by brutalsavage** [ShiftLeftSecurity/codepropertygraph#1321]
columnNumber is not correct when function is parsed by c2cpg instead of directly using Joern

./c2cpg.sh <your/source/directory> -o /tmp/cpg.bin

file:
```
int main() {
int a = 0;
statementthatdoesnothing();
int b = 0;
int c = 0;
}
```

and then load the parsed bin into Joern:

however here is the Joern output with the columnNumber of the identifiers: 

```
Identifier(
    id -> 4611686018427887959L,
    argumentIndex -> 1,
    argumentName -> None,
    code -> "a",
    columnNumber -> Some(value = 4),
    lineNumber -> Some(value = 2),
    name -> "a",
    order -> 1,
    typeFullName -> "int"
  ),
  Identifier(
    id -> 4611686018427887964L,
    argumentIndex -> 1,
    argumentName -> None,
    code -> "b",
    columnNumber -> Some(value = 6),
    lineNumber -> Some(value = 4),
    name -> "b",
    order -> 1,
    typeFullName -> "int"
  ),
  Identifier(
    id -> 4611686018427887968L,
    argumentIndex -> 1,
    argumentName -> None,
    code -> "c",
    columnNumber -> Some(value = 7),
    lineNumber -> Some(value = 5),
    name -> "c",
    order -> 1,
    typeFullName -> "int"
  )
```

we see that each of the identifier (a, b, c) has different column numbers even though they should be on the same column. When parsing this file directly in Joern without c2cpg, the output for the column number is correct.

**Comment by max-leuthaeuser** [comment]
Thanks for the report, you are right.
It's fixed with the linked PR.

**Comment by brutalsavage** [comment]
@max-leuthaeuser @fabsx00 I don't think the issue has been fixed
see this example: 
```
void offset() {
char * data = NULL;
memset(data, 'A', 100-1); /* fill with 'A's */
data = dataBuffer;    
}
```
here is the joern output with the columnNumber after being processed by the newest codepropertygraph c2cpg

```
 Identifier(
    id -> 1000105L,
    argumentIndex -> 1,
    argumentName -> None,
    code -> "data",
    columnNumber -> Some(value = 8),
    lineNumber -> Some(value = 2),
    name -> "data",
    order -> 1,
    typeFullName -> "char"
  ),
  Identifier(
    id -> 1000106L,
    argumentIndex -> 2,
    argumentName -> None,
    code -> "NULL",
    columnNumber -> Some(value = 15),
    lineNumber -> Some(value = 2),
    name -> "NULL",
    order -> 2,
    typeFullName -> "ANY"
  ),
  Identifier(
    id -> 1000108L,
    argumentIndex -> 1,
    argumentName -> None,
    code -> "data",
    columnNumber -> Some(value = 9),
    lineNumber -> Some(value = 3),
    name -> "data",
    order -> 1,
    typeFullName -> "char"
  ),
  Identifier(
    id -> 1000114L,
    argumentIndex -> 1,
    argumentName -> None,
    code -> "data",
    columnNumber -> Some(value = 3),
    lineNumber -> Some(value = 4),
    name -> "data",
    order -> 1,
    typeFullName -> "char"
  ),
  Identifier(
    id -> 1000115L,
    argumentIndex -> 2,
    argumentName -> None,
    code -> "dataBuffer",
    columnNumber -> Some(value = 10),
    lineNumber -> Some(value = 4),
    name -> "dataBuffer",
    order -> 2,
    typeFullName -> "ANY"
  )
```

we see that the identifier `data` in line 2, 3 and also identifier `dataBuffer` in line 4 in the code should be all on the same column, but the columnNumber is difference (increased by 1 each time). Again tested this by parsing directly in Joern and the output is correct.

**Comment by max-leuthaeuser** [comment]
Ok, I'll investigate what's going on.

**Comment by max-leuthaeuser** [comment]
Are you sure you have tested that with the latest c2cpg in master?
I added your example as testcase here: https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1326
and it works as expected.

**Comment by max-leuthaeuser** [comment]
Yes.. Indeed \r\n is counted as two characters when invoking String#length.
You might want to try it again with https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1328 in.

**Comment by brutalsavage** [comment]
I tried again with the new changes and it doesn't seem like the issue is fixed with the CRLF files. You can test this by creating a test file and use the dos2unix and unix2dos commands to switch the test file between the two file formats (CRLF and LF).

**Comment by max-leuthaeuser** [comment]
You want to try it again once https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1333 is in.

**Comment by fabsx00** [comment]
Should now also be available on joern master.
