### ISSUE TITLE
@q annotation broken for queries with required parameters

### ISSUE THREAD

**Issue by johannescoetzee** [ShiftLeftSecurity/codepropertygraph#1334]
We came across this issue when writing testcases for the `query-database` package. In that case specifically, the following code snippet would not return queries (methods with the `@q` annotation) that had parameters without default values set. 
```
  def allQueries: List[Query] = {
    new QueryDatabase().queriesInBundle(queryBundle.getClass)
  }
```

This wasn't caught by the `QueryDatabaseTests`, since the example query used there specifies a default value for the parameter:

```
object TestBundle extends QueryBundle {
  @q def foo(n: Int = 4): Query = Query(
    ...
  )
}
```

**Comment by ursachec** [comment]
We now throw an exception when attempting to retrieve the queries from a query bundle which has an annotated, query creating, method with a parameter without a default value. https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1337
