### ISSUE TITLE
parserTypeName and typeFullName inconsistencies between fuzzyc2cpg and c2cpg

### ISSUE THREAD

**Issue by johannescoetzee** [ShiftLeftSecurity/codepropertygraph#1343]
While testing the queries in https://github.com/joernio/query-database using the new frontend, I came across two inconsistencies between `fuzzyc2cpg` and `c2cpg` that broke some of the existing queries.

1. The `parserTypeName` for `ControlStructure` nodes now has `CAST` or `CPPAST` prepended (so `IfStatement` becomes `CASTIfStatement`). This breaks the querydb query checking loop count. Modifying queries to use the new naming convention is simple if we choose to do so, ~but updating the `parserTypeName` in the CPG feels like a neater solution~. Updating the queries to use the `controlStructureType` instead is  much less fragile.
2. Pointer type information is lost from the CPG when using the new parser. For example:
```
void bad(a_struct_type *a_struct) {
  void *x = NULL;
  a_struct->foo = x;
  free(x);
}
```
The fuzzy front-end would give `typeFullName -> "a_struct_type *"` and `name -> "a_struct"` while the new front-end gives `typeFullName -> "a_struct_type"` and `name -> "a_struct"`. The fact that `a_struct` is a pointer is no longer encoded in the `MethodParameterIn` node.

**Comment by max-leuthaeuser** [comment]
Thanks for that!

1) Yes, `controlStructureType` should be used. `parserTypeName` was only used in fuzzyc2cpg because we had no `controlStructureType` back in the days.
2) This will be fixed. Don't know why this was not present in the tests yet.
