### ISSUE TITLE
Possibly unwanted #ifdef behaviour when running joern-scan with new C frontend

### ISSUE THREAD

**Issue by johannescoetzee** [ShiftLeftSecurity/codepropertygraph#1368]
I'm creating this issue here instead of in the joern repo, since I think this is related to the parser used for the new C frontend, rather than joern scan. 

Example source:
```
#ifdef SOMETHING
void vulnerable_in_ifdef(char *dst, char *src) {
        strcpy(dst, src);
}
#endif

void vulnerable_not_in_ifdef(char *dst, char *src) {
        strcpy(dst, src);
}    
```

Example output:
```
❯ ./joern-scan --overwrite --language newc ../../test_repos/test_project/ifdef --tags badfn

Result: 4.0 : Dangerous functions `strcpy` or `strncpy` used: /home/johannes/code/test_repos/test_project/ifdef/ifdef_test.c:8:vulnerable_not_in_ifdef
```

If I add `#define SOMETHING` to the top of the file, then I get the output I would've expected:
```
❯ ./joern-scan --overwrite --language newc ../../test_repos/test_project/ifdef --tags badfn
Result: 4.0 : Dangerous functions `strcpy` or `strncpy` used: /home/johannes/code/test_repos/test_project/ifdef/ifdef_test.c:4:vulnerable_in_ifdef
Result: 4.0 : Dangerous functions `strcpy` or `strncpy` used: /home/johannes/code/test_repos/test_project/ifdef/ifdef_test.c:9:vulnerable_not_in_ifdef
```

It feels like this intelligent handling of `#ifdef` directives could lead to potential vulnerabilities being missed, but it could also avoid some false positives. At the very least, I think this behaviour is something we should consider, one way or the other.

**Comment by johannescoetzee** [comment]
I forgot to mention that this was tested with the WIP branch from ://github.com/ShiftLeftSecurity/codepropertygraph/pull/1366, before the commit to switch to static dispatch.

**Comment by max-leuthaeuser** [comment]
This is fully intentional.
fuzzyc2cpg was able to simply parse around such preprocessor statements (being a fuzzy parser).
But within c2cpg using Eclipse CDT we now have a full fledged C/C++ parser relying on such things (e.g., #define) etc.

More info: https://wiki.eclipse.org/CDT/designs/Overview_of_Parsing#Scanning_and_Preprocessing

**Comment by max-leuthaeuser** [comment]
You can also run c2cpg with the `--define` parameter do set defines from the outside.
And inspect all available defines with `--log-preprocessor`.

**Comment by johannescoetzee** [comment]
Ah, great! Closing this issue since this is working as intended then.
