### ISSUE TITLE
Some operators have the wrong name (typo)

### ISSUE THREAD

**Issue by max-leuthaeuser** [ShiftLeftSecurity/codepropertygraph#1629]
@mpollmeier 
See: https://github.com/ShiftLeftSecurity/codepropertygraph/blob/master/schema/src/main/scala/io/shiftleft/codepropertygraph/schema/Operators.scala#L94

Some operators are prefixed with `<operators>` while others got `<operator>`

(For: https://github.com/joernio/joern/issues/1348)

**Comment by mpollmeier** [comment]
This is indeed a little mistake/typo, but unfortunately fixing these constants would be a backwards incompatible change. There are situations where we introduce breaking changes, but I don't think fixing some typos is a strong enough mandate. 

For now we'll just add a TODO, and can make the change next time there's a breaking change:
https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1630
