### ISSUE TITLE
Poor CPG representation

### ISSUE THREAD

**Issue by llooFlashooll** [ShiftLeftSecurity/codepropertygraph#1792]
Hi folks, I really appreciate your work, and realize Joern highly depends on this package.

However, I find the representation of this CPG is poor. For example, here are my practices,
- This package cannot neatly return a tree for the CFG such as `cpg.cfgNode.toList`. If we want the tree, we need to select a starting node and then perform a DFS/BFS to get a tree on our own;
- The AST representation is too simple. Compared to the Python native AST library, this package only supports limited syntaxes. For instance, if there is an assignment statement, this package cannot return the left and right hand side of the statement.
- The traversal on CPG is not good. this package just dumps all the things without enough logical connection on any representation such as AST, CFG, call graph.

I want to implement heavy static analysis based on your work. However, I was stuck in the early stage. If you can give some suggestions, I would really appreciate it! Thank you very much!

**Comment by mpollmeier** [comment]
discussion continued in https://github.com/joernio/joern/issues/5098
