### ISSUE TITLE
Perform all CPG loading via CpgLoader

### ISSUE THREAD

**Issue by fabsx00** [ShiftLeftSecurity/codepropertygraph#292]
We currently have two public classes for CPG loading: CPGLoader and ProtoCpgLoader. This is due to the fact that we supported multiple CPG formats in the past. As of today, only the proto format survived. As I was documenting CPG loading, I was wondering whether we should make ProtoCpgLoader a private class that provides the default implementation for CpgLoader. Let's locate all the places where ProtoCpgLoader is used directly and see if we can instead use CpgLoader. If this is not possible, we may need to make modifications to CpgLoader.

If this all works well, I think we should round off the CPG loading topic by creating unit tests against `CpgLoader`. What do you guys think?

**Comment by mpollmeier** [comment]
Agreed, that makes sense. @lifecoder can you take this?

**Comment by lifecoder** [comment]
@mpollmeier Sure

**Comment by lifecoder** [comment]
It is used by fuzzyc2cpg and codescience/cpgqueryingtests:
https://github.com/ShiftLeftSecurity/fuzzyc2cpg/blob/29dbc250f8d75fe3be8dd8f910e16f513f0b3108/src/main/java/io/shiftleft/fuzzyc2cpg/output/inmemory/OutputModule.java#L54

codescience/cpgqueryingtests:
https://github.com/ShiftLeftSecurity/codescience/blob/5c2e6618a86ed984b88ecf68df1568cb5dd8459e/cpgqueryingtests/src/test/scala/io/shiftleft/cpgqueryingtests/codepropertygraph/ProtoCpgTestFixture.scala#L60

https://github.com/ShiftLeftSecurity/codescience/blob/d3f81a3b70e06b16b63bfc9a013997d55318cab7/cpgqueryingtests/src/test/scala/io/shiftleft/cpgqueryingtests/codepropertygraph/CpgPreprocessor.scala#L58

**Comment by fabsx00** [comment]
Concerning this ticket: I just found that `cpgqueryingtests` in `codescience` actually has a few tests for CPG loading based on the proto loader (ProtoLoaderTests). However, those tests are full-on integration tests and the fact that this is a bad idea is pointed out in a TODO. After gettings tests into `codepropertygraph` for CpgLoading, I think it's fine if we remove those tests in `codescience`.

**Comment by mpollmeier** [comment]
@lifecoder just so you don't get confused, the TODO @fabsx00 refers to is not the one in the test, but the one in ProtoCpgTestFixture:
```
// TODO Rewirte this tests. This is acutally a full integration test which is way to much here.
// What we need is some code which composes a proto CPG structure, feed this structure to the ProtoCpgLoader
// and than query the graph. But query the graph without our cpg steps. Pure gremlin scala to keep it simple and
// separated.
```

**Comment by fabsx00** [comment]
Correct.

**Comment by fabsx00** [comment]
Added tests: https://github.com/ShiftLeftSecurity/codepropertygraph/pull/339

**Comment by fabsx00** [comment]
Outdated.
