### ISSUE TITLE
I can't generate with ocular a complete Graph ? 

### ISSUE THREAD

**Issue by omah69** [ShiftLeftSecurity/codepropertygraph#313]
Hello, 

I created a binary CPG from Jar file and I loaded it in ocular 

`ocular> loadCpg("log4j.bin.zip")`

And then I export it in JSON format: 

`ocular> cpg.method.toJson |> "/tmp/log4j.json"`

The JSON Format is not the one I need, because it's not full, there is only methods.. . I need I full graph representation with alls nodes and edges etc.. The format sould by like this file [base.json](https://github.com/ShiftLeftSecurity/codepropertygraph/blob/master/codepropertygraph/src/main/resources/schemas/base.json)

So how can I do ? there a command to execue in ocular ?

Thanks in advance for your help.

**Comment by GlassAndOneHalf** [comment]
Hi @omah69 

You should be able to generate a complete CPG in JSON format using:
```
cpg.all.toJson
```

Please feel free to re-open the issue if this doesn't solve your problem.
