### ISSUE TITLE
Document `parameter` step

### ISSUE THREAD

**Issue by bbrehm** [ShiftLeftSecurity/codepropertygraph#526]
We recently had some confusion caused by a mixup between the `argument` and `parameter` step.

One possible usage of the `parameter` step is to traverse from a `Method` node to its formal parameter nodes.

However, `parameter` is defined for `ExpressionBase`. So we should document whatever it is supposed to do on Expression nodes that are not Method, potentially move the definition away from ExpressionBase, and potentially throw a runtime exception when called on something that is not of type Method.

**Comment by mpollmeier** [comment]
reassigned to @ml86, I think he's the best person to answer this - let me know if you disagree

**Comment by ml86** [comment]
I extended the step documentation. See the linked PR.
