### ISSUE TITLE
WithinMethods: messy?

### ISSUE THREAD

**Issue by mpollmeier** [ShiftLeftSecurity/codepropertygraph#610]
`WithinMethod` is a quite widely used trait: given it's name, I would have expected e.g. the subclasses `MethodReturn`, `MethodParameter[In|Out]` etc. 
However, because `TrackingPoint extends WithinMethod` and `Expression extends TrackingPoint`, almost everything extends `WithinMethod`. 

Is that design intentional or did we end up here accidentally? 
Just want to gather some more context while I'm refactoring the DSL.

**Comment by ml86** [comment]
All nodes which belong to a METHOD aka which are below a METHOD node in the AST, are of trait WITHIN_METHOD. Originally I used this trait to attach the `.method` step. I think it is still not used for much else. These days I think it is arguable whether this justifies a trait. So if this makes problems lets discuss.

**Comment by mpollmeier** [comment]
> All nodes which belong to a METHOD aka which are below a METHOD node in the AST, are of trait WITHIN_METHOD

Yes that was my understanding when I read the code and it would make sense, however as described above, every `Expression` is also a `WithinMethod`, which doesn't sound right. 
The confusion probably comes from the fact that an Expression _may_ be within a method, but not _every_ one is. The way the schema is defined right now, it indicates that the latter is correct, which it is not :)

The cleanest way may indeed be to remove that trait, and handle it in the traversals.

**Comment by ml86** [comment]
`Expression` being a `WithinMethod` is correct. I think that is where the confusion comes from. In our CPG no `Expression` outside of a method is allowed.

**Comment by mpollmeier** [comment]
Good to know, thanks for clarifying!
