### ISSUE TITLE
Load existing CPG without creating cpgclientlib

### ISSUE THREAD

**Issue by jaiverma** [ShiftLeftSecurity/codepropertygraph#664]
Is there a way to load an existing CPG without creating a new one?
I only see a `create_cpg` function in `cpgclientlib`.

**Comment by ursachec** [comment]
Yes @jaiverma, you can use `importCpg("/path/to/cpg")` top-level command for that

**Comment by jaiverma** [comment]
@ursachec I actually meant if it's possible through the Python API and not through the Joern REPL. But I don't need this feature anymore. Thanks!
