### ISSUE TITLE
`expression.start.inCall` works but `expression.inCall` does not

### ISSUE THREAD

**Issue by fabsx00** [ShiftLeftSecurity/codepropertygraph#957]
Regarding our discussion about ensuring that `.foo` always works when `.start.foo` works, I am wondering whether this is a corner case or whether I'm just missing an import:

`expression.start.inCall` follows incoming argument edges to reach the call for an argument, however, `expression.inCall` seems to not work.

**Comment by mpollmeier** [comment]
It's kind of an edge case... that being said it does occur a few times :)
`Traversal[Expression].inCall` is defined only for a Traversal: (https://github.com/ShiftLeftSecurity/codepropertygraph/blob/master/semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/expressions/generalizations/Expression.scala#L52-L53),
and we do not currently have an implicit that lifts a single node into a Traversal. 
Maybe it's time to change that though - I'll give it a try and will see if there's any significant downsides.

**Comment by mpollmeier** [comment]
fixed via https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1007 and https://github.com/ShiftLeftSecurity/codescience/pull/4372
